### PR TITLE
Add support for Heroku Deploy resolves #142

### LINKED ISSUE #142: Feature Request: Heroku deploy option
Add a deploy to heroku button.

### PR DESCRIPTION
**Pull request by BadPirate**
Added heroku deploy button and support to quickly deploy your own coinb.in instance on heroku.

### CODE REVIEW

**Comment by BadPirate** [comment]
Fixes #142

**Comment by brrbrrpatapim4** [comment]
@ciyam hey there, i've been trying to contact you, have something very interesting for you to take a look at, please email me at evpsocials@gmail.com!

**Comment by Ouhly10** [comment]
Hey there , what’s up!

**Comment by brrbrrpatapim4** [comment]
Hey @Ouhly10 are you in contact with Ian Knowles / @ciyam?

**Comment by Ouhly10** [comment]
No, I am not.

**Comment by brrbrrpatapim4** [comment]
do you know of him?

**Comment by Ouhly10** [comment]
No, why?

**Pull request closed without merging**
