### PR TITLE
Add Bitcoin Cash Support

### PR DESCRIPTION
**Pull request by dabura667**
Fixes #111 and fulfills the bounty ($50? $75?) stated in #112

@imcoddy @NxtChg @globaltoken

Let me know if this needs fixing or anything. I have no BCH to test with.

### CODE REVIEW

**Comment by dabura667** [comment]
@OutCast3k Also notice this changes sighash logic a tad. since ANYONECANPAY and SIGHASH_FORKID are both masks, they shouldn't be checked using >= etc. so I moved around the logic and cleaned up the ANYONECANPAY logic so that I could insert the & 0x40 logic in afterward.

**Comment by NxtChg** [comment]
Awesome! It will take me a while to backport this to my wallet, but if it works, you'll get the $50 bounty.

**Comment by NxtChg** [comment]
I am getting an error: "mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26"

I've added 0x40 when calculating tx hash, and also to serialize_sig():

```
	return serialize_sig(r,s).concat([1 | 0x40]);
```

Is this correct?

**Comment by NxtChg** [comment]
@dabura667 It's working. Tell me your bitcoin address and I will send you the last milestone ($30). To be fair, the first one should be claimed by @globaltoken who added the blockdozer's API.

**Comment by NxtChg** [comment]
It's alive: http://simcoin.info/tsbw/bcc/

**Comment by dabura667** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkDbcHiZ z1KmaVGP2MwDu8W IeOGWy46RgXq0vo vyO9lixKuQjdxNL R1pD4hb8VAcJVix 7OETjVUnxnlSMsp VJDAncNjgy0JNaB m3LBTTvc2GLqcwD tNd0pd6X8DKCv0A zejwHZGbT3rUJRK 5dJBlktrJJAbr0Q JTtdHTBxXPnLWbk 3CHmSyMwDtLf35d Fd9qXI4IdLjya1X UXQPIlnBDn7Z1SU gHwOWWezfjtTc6o 8Z97gLirFtvvvw6 cM6W0mIx0BefL4H 1BxNtmwpEXvlqrn X6XhIyhVLXyMRHv m. END KEYBASE SALTPACK SIGNED MESSAGE.

Paste this into https://keybase.io/verify and click verify and you'll get my address.

Thanks

**Comment by NxtChg** [comment]
@dabura667 Sent: https://blockchain.info/tx/45dd312ecc599c01c9bf01aef0d19f6e7fd272b861090383ae3da5caa15b6f2a

**Comment by globaltoken** [comment]
It shows for me again with your Code: "16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID). Code:-26"

**Comment by globaltoken** [comment]
You must add 6 more Cases for:

> SIGHASH_ALL|SIGHASH_FORKID
SIGHASH_NONE|SIGHASH_FORKID
SIGHASH_SINGLE|SIGHASH_FORKID
SIGHASH_ALL|SIGHASH_ANYONECANPAY|SIGHASH_FORKID
SIGHASH_NONE|SIGHASH_ANYONECANPAY|SIGHASH_FORKID
SIGHASH_SINGLE|SIGHASH_ANYONECANPAY|SIGHASH_FORKID

Because BCC Code has it all too.

**Comment by NxtChg** [comment]
> It shows for me again with your Code: "16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID). Code:-26"

You need to change here too:  `var sig = serializeSig(r, s); sig.push(parseInt(1, 10));`

BTW, tell me your bitcoin address, I want to send you $20 bounty for adding blockdozer API.

**Comment by globaltoken** [comment]
My Address is: 1GMVNycJsqTLtorHB1D8xLYeYp1asvpJJJ

Where is this variable?

**Comment by NxtChg** [comment]
Sent: https://blockchain.info/tx/c99af46b80fb7845d15dd8b5479f34cd585a5723fda9529861df0c681736c9ce

**Comment by globaltoken** [comment]
Thanks mate :)

**Comment by dabura667** [comment]
@globaltoken I have them all taken care of, if you follow each one logically through the transaction hash function all the conditions will be met.

@NxtChg *sigh* could you make a pull request to my bitcoincash branch, I am away from my PC for 3 days.

Am I going to have to hunt down every instance where the sighash is assumed to always be 1 in the source now?

Doesn't that also mean that all the sighash stuff he added a few months ago was meaningless since it always assumes to place the 1 after the signature anyways? lol

**Comment by globaltoken** [comment]
Anyways signing did not worked with this Code for me, If I try broadcast to BCC Network it's saying the same Error, So I cannot Sign correctly my BCC Transaction with this Code.

I think you must define your Cases correctly here: https://github.com/OutCast3k/coinbin/blob/master/index.html#L922

Thats why he thinks its normal BTC Transaction.

**Comment by dabura667** [comment]
@globaltoken fixed the problem.

**Comment by globaltoken** [comment]
Okay let me check again mate :)

**Comment by dabura667** [comment]
No need to define the FORKID sighash in there, since it is required for Bitcoin Cash and is forbidden for any other crypto. Adding the option to remove it makes no sense.

So when the user is using BCC, the code will automatically add FORKID sighashing logic in the background on top of whatever sighash the user chose.

**Comment by globaltoken** [comment]
Seems difficult.
I receive now this Error:

> 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

Regards

**Comment by dabura667** [comment]
That error is not from the sighash.

You are likely signing the input with the wrong private key.

Could you explain the situation and what you are trying to sign? (Is in single sig, multisig, what sighash are you trying to use etc etc)

**Comment by NxtChg** [comment]
> @NxtChg sigh could you make a pull request to my bitcoincash branch, I am away from my PC for 3 days.

Not sure what you mean, I don't edit coinb.in, I edit my own wallet, which is a simplified version: https://github.com/NxtChg/tsbw

> Am I going to have to hunt down every instance where the sighash is assumed to always be 1 in the source now?

There are only 2 places: one you fixed, another I posted, after serializeSig().

>Doesn't that also mean that all the sighash stuff he added a few months ago was meaningless since it always assumes to place the 1 after the signature anyways? lol

Yeah, seems like it :)

**Comment by globaltoken** [comment]
It is a Single Address not Multisign.
And yes it is the Correct Private Key which was used to Sign the Transaction.

**Comment by dabura667** [comment]
@globaltoken could you share the data being hashed?

Before `var r = Crypto.util.bytesToHex(coinjs.hash256(buffer));`

And before `return buffer` on the three new functions for preparing prevouts, sequences, and outputs.

Could you insert
`console.log(Crypto.util.bytesToHex(buffer));`
And tell me what each one says?

**Comment by dabura667** [comment]
@globaltoken you can encrypt it for me at https://keybase.io/encrypt and type in dabura667 as the person you want to encrypt it for.

**Comment by AArnott** [comment]
Thanks for your work here, @dabura667.

I used your fork to create and sign a BCC transaction, but when broadcasting it, it's rejected. I am not sure whether it's because the BCC network is confused about a BTC transaction I've already made to split my coins, or if it's because the coinbin fork didn't properly create or sign the transaction.

Here is the transaction I am trying to broadcast: 

```
010000000170e218568995588b9697a296c6e4f95da8f5498ded0f0010a4248db171d7639f00000000fdfe0000483045022100ab88a13207f3a3cf583408f897a5f49ce21a6ca74e2bb28503498787b50666f70220216b8589bb968e479748f361af8ed785b34a7632a48ad6b2953663b8bb4eb7d501483045022100d2cd2f568a51181ae435a13716036bc9107f9da12b53e26d526af9af3fb62adc022017f0574fa30734c43ae9a959b8dee35db6996c8697a71af446132b6a061340c8014c695221021e7387bf7de0464c6f142af66ed090f2095e2dcd958c3c4f2559e124833b802f2103507700281a1c5b3618c4cdb3b96746a991965a12bbc06cc1f05b6eec8031c534210372723debd1822141a6a9e400d52d0eb2cbae885770f37fcacfa0f02688fa4a4753aeffffffff01c08f4b00000000001976a9145d0807b7a18c844ed65dc2df3fcf075d19957cf388ac00000000
```

When I try to broadcast this transaction though, your coinbase fork reports `Missing inputs`. Other web applications also reject the tx when I try to broadcast it, such as https://blockr.io/tx/push

If your coinbin has no defects (and assuming I'm using it properly) then the issue might be that the BCC network itself is buggy. For example, when I use `electron-cash` on my source address, I get this output:

```
./electron-cash  getaddresshistory 3AMwRjkvGKim351tdMtipoLekecfNzF1KW
[
    {
        "height": 451597,
        "tx_hash": "9f63d771b18d24a410000fed8d49f5a85df9e4c696a297968b5895895618e270"
    },
    {
        "fee": 40000,
        "height": 0,
        "tx_hash": "976eff55d76bdf1dd13c6ce26d4012eb3c980a6109f0bc94c07e2992a18e1dbf"
    }
]
```

The first transaction is legit (it happened before the fork). But the second transaction is a BTC transaction that happened after the fork. 
Note that blockr.io can find the first transaction, but not the second. Yet blockr.io still rejects the transaction I made with your coinbase fork.

**Comment by AArnott** [comment]
@dabura667 Yes, I generated the transaction using your fork. What do you mean it has posted? I can't find any evidence of that. Every attempt to broadcast it has failed, and the address it's pulling money from [does not show any spend transaction](http://blockdozer.com/insight/address/3AMwRjkvGKim351tdMtipoLekecfNzF1KW).

BTW, I'm willing to throw in .13 BCC (or equivalent BTC) as a bounty for help that unblocks this transaction.

**Comment by NxtChg** [comment]
@AArnott try http://simcoin.info/tsbw/bcc/ - it sends txs just fine.

**Comment by dabura667** [comment]
I meant posted as in you posted it to github in your comment.

It looks like the bitcoin cash detection is broken.

Are you selecting Blockdozer (Bitcoin Cash) in the settings panel before doing anything else?

**Comment by AArnott** [comment]
Thanks. I hadn't gone to the Settings panel. I've now done that, and recreated the transaction and re-signed it. I have a different transaction now:

`010000000170e218568995588b9697a296c6e4f95da8f5498ded0f0010a4248db171d7639f00000000fc004730440220169bd2cac21aca87e813035ea09cfb5e820de3aa1a1ce5c876dd2fa57b74a678022005a4af8798c7856bb0a96dac7ef2093285b627eb453254b5d929bcb87b2282d04147304402205ba4b0a6a111a5fe6c5d9730e19d43a2547371ae989e75d60c85609e15e52e5a02203c3464d3db0925e148f575a5f0f33a504e91d4f71c4f3c6ba0b9591bc500e97a414c695221021e7387bf7de0464c6f142af66ed090f2095e2dcd958c3c4f2559e124833b802f2103507700281a1c5b3618c4cdb3b96746a991965a12bbc06cc1f05b6eec8031c534210372723debd1822141a6a9e400d52d0eb2cbae885770f37fcacfa0f02688fa4a4753aeffffffff01c08f4b00000000001976a9145d0807b7a18c844ed65dc2df3fcf075d19957cf388ac00000000`

But coinbin is still reporting missing inputs when I try to broadcast it.

**Comment by AArnott** [comment]
BTW when I try to broadcast this same transaction with the electron-cash client, I get this error:

> error: The transaction was rejected by network rules.  (258: txn-mempool-conflict)

**Comment by dabura667** [comment]
mempool conflict means the input is already used in another transaction. This is also the error when that transaction itself is already broadcasted

**Comment by dabura667** [comment]
Also perhaps something in the input checking logic is assuming the sighash should be 01...

If the error is a mempool error, It sounds like my pull request is working.

**Comment by AArnott** [comment]
Thanks. That's what I was afraid of. I guess I need to go file a bug with the Bitcoin Cash node repo.

**Comment by dabura667** [comment]
@globaltoken I found the problem.

When you copy and paste a transaction from the transaction tab to the sign tab, it is re-instanciating the transaction object from the pasted raw transaction which obviously does not contain the values of each input, so each input value is being signed as 0 satoshis thus causing the error.

I now search for the address of each input, (I don't know how hodl works and wasn't bothered to find out, if you want to tell me what to do for its address, let me know thanks) and query its balance synchronously.

hacky, but it worked just now.

@AArnott maybe this will fix your problem too.

**Comment by AArnott** [comment]
Thanks, @dabura667. I have a new problem now (earlier in the process). Now when I try to sign the transaction, I get this error:

> Can not retreive input values for Bitcoin Cash signatures.

Any ideas?

**Comment by dabura667** [comment]
That means that the utxo data is not available from the API. Since your original error was `(258: txn-mempool-conflict)` then it makes sense that the data is not available.

**Comment by dabura667** [comment]
You can not broadcast or sign the transaction because the transaction you are referencing in your input most likely doesn't exist OR is referenced in a previous transaction.

**Comment by AArnott** [comment]
Thanks. 
Curious why the problem is at signing rather than at formulating the transaction in the first place. I would expect the original creation of the transaction would be the point of failure since that would have to have identified the sources of funding. The nutty part is, the Load button on the New Transaction form _does_ correctly identify the input transaction. Everything looks good on that screen. And since signing doesn't look up anything from the network, how can it be failing at that stage?

But ya, ultimately I may have a problem with the BCC mempool having a stray transaction sitting in it even though it isn't signed for BCC. I looked for a github project to report the issue on and couldn't find one. :(

**Comment by dabura667** [comment]
http://blockdozer.com/insight-api/addr/3AMwRjkvGKim351tdMtipoLekecfNzF1KW/utxo

Actually it looks like the API is giving the right info... maybe my code isn't getting the address right?...

But it should definitely get the mutlisig detection correct...

This is weird...

**Comment by AArnott** [comment]
I just tried it with a different source address (but also one already spent on the BTC network) and got the same errors. But all my funds are from multi-sig addresses so I can't test a simpler case.

**Comment by dabura667** [comment]
I will send you a chat on keybase.

**Comment by dabura667** [comment]
Could someone send a small amount of BCC to my new multisig I just made. I would like to test.

3NnieuX81X82D6v2aFAqP8RWRtspDQHJgY

**Comment by AArnott** [comment]
You did it, @dabura667! That last fix got my transaction to broadcast. *Thank you*.
I'll ping you on keybase to arrange paying my promised bounty.

**Comment by currentsea** [comment]
I have used dabura's fork to broadcast a P2SH transaction successfully.

**Comment by currentsea** [comment]
If anyone uses the coinb.in HODL based addresses,i have a pull request opened to this same branch (the one that was authored by dabura667) that makes the change support HODL addresses for BCH as well: 

https://github.com/dabura667/coinbin/pull/2

**Comment by dabura667** [comment]
rebased

Segwit and Bitcoin Cash on one branch... oooh riskaaaayyyyyy.

**Comment by AArnott** [comment]
@dabura667 FWIW I'm not a fan of rebasing public PR commits. In this particular instance, I've already written a blog post that refers to your commits so that folks can follow instructions I've written up and know that the user will use a version that behaves exactly the way my instructions will fit to. When you rebase, your original commits are no longer in history, which if your PR eventually merges means the commits I refer to will never appear in official history (and might eventually be pruned so users can't find them, if I hadn't forked to ensure that didn't happen).

**Comment by dabura667** [comment]
@AArnott Sorry you feel that way... :-( wished I had known before hand.

I personally follow the dogma that:

1. There are certain branches that should never have history overwritten: (master, development, staging, and tagged versions which are branched off these with backports where needed.)
2. PR branches can be rebased and reordered and completely destroyed whenever. The most volatile.
3. Once merged to a protected branch, the commit hashes are set in stone (hopefully signed by the merging party)

Though I guess in this specific instance, this PR has a low chance of being merged, so a lot of people just assumed the best they could get was my branch, and so people were using my branch as a "protected branch" use case.

hmmm... if you have a local branch with the old state could you push it to github and I'll try pulling it from you and pushing it back. Then I guess I can merge master in this branch with a merge commit.

**Comment by AArnott** [comment]
> wished I had known before hand.

Not a big deal, since I did maintain a fork of your fork just in case this happened. The dogma you reference is fairly common, and I do occasionally rebase my own PRs, especially short-lived ones that no one else is likely to have taken a dependency on.

> if you have a local branch with the old state could you push it to github 

I do have my fork of yours: https://github.com/AArnott/coinbin/tree/bitcoincash
But I don't think you need it, actually. You can use `git reflog` to see what commit you were on before you rebased and do a `git reset --hard` back to it in order to undo your rebase. IMO that would be the best option. Merging my version of your commits with your newly rebased ones would just make double history, which might be more confusing than the small worth it would be to preserve the original ones.

But again, probably not a big deal. You actually taught me about "Verified" commits on github so I've started signing my own as well. And folks can see you signed the commits that are preserved by my fork, so I guess my blog readers will know my story is true, even if the commits are no longer on your PR.

**Comment by dabura667** [comment]
@AArnott I restored the old commits so any direct references to the hashes should work.

**Comment by Overtorment** [comment]
@AArnott your fork helped me a lot in retreiving BCH, thanks!

**Comment by surg0r** [comment]
Hi,

I have been trying for some time to move some BCH unsuccessfully held within a 2-of-3 multi-sig coinbin address (now empty of BTC funds).

In essence the problem I have encountered running both the @AArnott and @dabura667 latest fork codebases locally in both Safari and Chrome is that I am unable to sign the transaction successfully. 

I click the 'sign' button and cursor activity briefly occurs but no green signature box appears below as normal. Given a normal tx sign of a multisig address with multiple inputs can take a few seconds I am fairly sure it isn't computing the signature.

To clarify, I have chosen the correct settings tab, successfully identified the BCH inputs, created the tx for signing with no problem whatsoever. 

To further clarify  if I copy and paste the unsigned tx string into a fresh version of the page (i.e. with bitcoin mainnet in settings tab) then the signing page works fine. But if I try and broadcast that tx then the rejection error described above ("16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID). Code:-26") prevents the tx being propagated.

It may be worth adding that this address has >1000 inputs but I managed to move the BTC out of the address by using small chunks of inputs in several transactions previously without issue.

Finally this is a non-trivial amount of BCH and I would appreciate some assistance in unravelling this error. I would be happy to offer a bounty to assist me in moving these funds into a standard BCH address.

**Comment by dabura667** [comment]
Hi.

> (i.e. with bitcoin mainnet in settings tab)

Nope, you want to choose bitcoin cash in the settings tab, otherwise it will not sign the bitcoin cash transaction properly.

**Comment by dabura667** [comment]
Just to clarify, you need to select `Blockdozer.com (Bitcoin Cash Mainnet)` in the settings page (There's a cog wheel button to select the options on the "Broadcast" page. Change all of those to "Bitcoin Cash Mainnet")

**Comment by dabura667** [comment]
Even though the settings are on the Broadcast page, they affect the entire site. So change those settings first THEN generate and sign and broadcast.

**Comment by surg0r** [comment]
Thanks for the prompt reply.

As my initial post states the problem is occurring ONLY when I have selected bitcoin cash from settings. Standard BTC signing works without issue. With bitcoin cash selected the inputs from the BCH chain are correctly collected from blockdozer. Signing however fails in this settings mode preventing me creating the finalised tx to broadcast.

**Comment by Overtorment** [comment]
@surg0r wild guess: check dev console in browser, and networking tab. I noticed that coinbin makes lots of ajax requests to bcash block explorer during signing (one per each signe input?), maybe theres an issue somewhere around here.
Also, you can try spending less outs per transaction, maybe 5 per tx..?
Hope it helps.

**Comment by dabura667** [comment]
Also: Are you trying to use special sighashes? Dont. Only use SIGHASH_ALL (the default)

**Comment by surg0r** [comment]
@dabura667 I am using the default SIGHASH setting

**Comment by dabura667** [comment]
@surg0r hmmm... could you throw a few console.log in there to see what the hash preimages are?

To be specific you would want to place logs for `buffer` right before lines:

https://github.com/dabura667/coinbin/blob/2f60502ec8c28d72ad0dbca21d26ca3198753f8d/js/coin.js#L1024
https://github.com/dabura667/coinbin/blob/2f60502ec8c28d72ad0dbca21d26ca3198753f8d/js/coin.js#L1040
https://github.com/dabura667/coinbin/blob/2f60502ec8c28d72ad0dbca21d26ca3198753f8d/js/coin.js#L1049
https://github.com/dabura667/coinbin/blob/2f60502ec8c28d72ad0dbca21d26ca3198753f8d/js/coin.js#L1061

Then post the data here. If you want, you can encrypt it using keybase.io @ https://keybase.io/encrypt#dabura667

The data at those points includes all the inputs and outputs including values of the transaction you're trying to sign.

There is no secret info in those buffer objects at those points.

**Comment by dabura667** [comment]
All four of those will probably go off for each input, so 4 lines x inputs... might be kinda long, but if you send it to me I'll check to make sure the hash you're signing isn't missing info.

**Comment by surg0r** [comment]
@dabura667 I have sent you a message on keybase..

**Comment by anton000** [comment]
@dabura667 Seems signing a tx with multiple vouts from different addresses causes a "Can not retrieve input values for Bitcoin Cash signatures" error. 

It seems after one output is signed, then copy pasted to the input box to be signed by a diff address, it now tries to retrieve vouts of an address not included in the tx. It seems previously signed vout addressis being mutated during retrieval and causes the incorrect address being queried on blockdozer.

**Comment by dabura667** [comment]
@surg0r @anton000 I decided to just plop it in the rawtx at the end, separated by | and modify the new transaction creation and signing transaction reading sections.

Atom fixed some formatting issues in some files so the diff is kinda messy, sorry.

**Comment by anton000** [comment]
@dabura667 Seems signing now proceeds correctly. Can infact verify a signed tx, but broadcasting causes "16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)."

here's rawtx: https://pastebin.com/KKymUHZw

**Comment by dabura667** [comment]
@anton000 The only info I can gather from this is that your signatures are invalid. I checked the transaction and there was no indication that there was a formatting issue, but I tried sending it myself and also got the same error..........

I would need to see the signature preimages to figure out if something is wrong with them...

see: https://github.com/OutCast3k/coinbin/pull/113#issuecomment-333367956

**Comment by ohad7** [comment]
@dabura667 It seems that blockdozer.com changed their API and their AJAX/CORS policy in some way that makes it impossible to query outputs and to submit transactions. I was able to overcome their AJAX by disabling security on the browser, however the raw transaction that's being generated contains special characters such as "|" and the API doesn't support that. It did work about a month ago though, but not any more.

**Comment by dabura667** [comment]
@ohad7 remove the | and everything after it manually.

**Comment by globaltoken** [comment]
You can try instead of Blockdozer the Bitcoin Cash Blockexplorer API.
It is the same CMS, so you dont need to change things.

https://bitcoincash.blockexplorer.com/api/
API Ref: (same for BCC Version): https://blockexplorer.com/api-ref

Regards.

**Comment by Warlock314** [comment]
I fixed the API problem for Bitcoin Cash. HODL transactions work again. You can sign offline with Bitcoin Cash now. http://www.motelmaya.com/BCH/BCH.html

**Comment by ohad7** [comment]
@Warlock314 Looking great, Is this based on this coinb.in repository? Can you publish the source code?

**Comment by Warlock314** [comment]
@ohad I copied it from a website that was probably based on github, but was all squished together. I cleaned up with https://www.10bestdesign.com/dirtymarkup/, then modified it so that I could recover my Bitcoin Cash from the HODL address when the time comes. I noticed the API broke later, then found some other stuff on a different site to fix it. I noticed the file saving feature for signing offline, so I copied that over too. I am not really a programmer, except for making some video games for fun. I panhandle for a living. You are welcome to copy it off the website.

**Comment by dabura667** [comment]
switched to blockexplorer and rebased on master

**Comment by zakrid** [comment]
Any updates on getting this merged?

Cheers

**Comment by AbdussamadA** [comment]
The signed raw transaction contains a pipe symbol followed by some hex at the bottom. What's up with that? It's a valid transaction after you remove all that.

**Comment by dabura667** [comment]
@AbdussamadA that's the input values.

If you want to use the hex raw data somewhere else, you need to remove them.

**Comment by dabura667** [comment]
But for signing they are needed.

**Comment by AbdussamadA** [comment]
The *signed* raw transaction contains pipe symbols. That's after it has been signed and is ready to be broadcast. The broadcast doesn't work with this tool either giving an error that "invalid raw transaction" because of the pipe symbol.

**Comment by dabura667** [comment]
That’s.............. what I said.

**Comment by AbdussamadA** [comment]
You said those are the input values needed for signing. But this is the signed transaction. It's not input into anything. It's broadcast.

**Comment by dabura667** [comment]
Multisig.

**Comment by AbdussamadA** [comment]
Ok my bad then. Maybe the broadcast part of it can remove those bits automatically? It gives an error that it's an invalid raw transaction.

**Comment by Stemby** [comment]
Hi,  
any news on this front?

Thank you!

Carlo

**Comment by OutCast3k** [comment]
coinb.in will not be adding bitcoin cash support, ever. but, i'm glad some of you have been able to fork it and make it work for yourselves. nice work.

**Comment by zilveer** [comment]
@dabura667 hi, glad that u managed to implement BCH.
Is there any chance that you can add the new BCH cash addresses as well?

Regards Zilveer

**Pull request closed without merging**
