### PR TITLE
Bitcoin Cash Integration + GlobalToken Integration

### PR DESCRIPTION
**Pull request by globaltoken**
I made an Update to Integrate Bitcoin Cash and Globaltoken.

### CODE REVIEW

**Comment by dabura667** [comment]
NACK, Bitcoin Cash is broken. This does not use BIP143 sighash with SIGHASH_FORKID.

**Comment by globaltoken** [comment]
Okay, let me check. Anyways - This Code worked for me

**Comment by dabura667** [comment]
> This Code worked for me

Did you actually broadcast a transaction you signed using coinb.in? No you didn't, because Bitcoin Cash transactions are not valid unless you use the new sighash FORKID (0x41) method.

Coinbin does not support sighash FORKID BIP143 based sighashing.

**Comment by globaltoken** [comment]
Let me check.
I try to integrate it.

**Comment by dabura667** [comment]
re: I am one of the developers that ported Electrum to Electron Cash. I know what I'm talking about.

If you have any questions about adding the new sighashing algorithm let me know and I can help you with any questions you have.

**Comment by globaltoken** [comment]
Okay mate, I will let you know here.

**Comment by globaltoken** [comment]
Ah okay now I see:

"64: non-mandatory-script-verify-flag (Signature must use SIGHASH_FORKID). Code:-26"

**Comment by globaltoken** [comment]
@dabura667 Is there anywhere a Documentation of these SIGHASH Types & Signature Code?
That would help :)

Or In which File is the Signature Applied for Bitcoin?
I searched the Source and Found SIGHASH_FORKID but couldn't find out where the Signature Part is.

Thank you.

**Comment by dabura667** [comment]
Specification with examples (though BIP143 was made with segwit in mind, some segwit-specific rules are ignored, but other than that the examples are very helpful)
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki

Also, there's a bitcoinjs-lib fork that implements it:
https://github.com/afk11/bitcoinjs-lib/blob/4a4b7fd0d403d5817b57c46f2e6c486c71b485dd/src/transaction.js

Follow the functions and read them:
Transaction.prototype.hashForCashSignature
which calls
Transaction.prototype.hashForWitnessV0

One issue that needs to be addressed that is kind of big: inputs in the transaction object need a satoshi amount attached to them, as the input value needs to be hashed.

**Comment by globaltoken** [comment]
Oh okay, I checked it and this seems to be a bigger Thing to implement it.

**Comment by globaltoken** [comment]
I looked into the bitcoinjs Lib but it's different because it uses NodeJS.
Some Requirements are not met here, so a new Code-Implementation would be necessary.

**Comment by dabura667** [comment]
Yeah. I didn't say "copy paste it." I said "look at it" lol.

ie. to get an idea of how you could implement it in coinb.in

If you can't, either remove the bits about Bitcoin Cash, or close the whole Pull Request.

**Comment by globaltoken** [comment]
I will create a new Pull Request when i got it.
Thanks for the notice.

**Comment by dabura667** [comment]
1. Modify addinput to include value as an arg, and add the value (or default null) to the pushed input
https://github.com/OutCast3k/coinbin/blob/master/js/coin.js#L779

2. Grab the value Number that is added to the value variable (u.getElementsByTagName("value")[0].childNodes[0].nodeValue*1) and pass it to the addinput here to make sure the inputs will always contain the values.
https://github.com/OutCast3k/coinbin/blob/master/js/coin.js#L884

3. The way SIGHASH_ANYONECANPAY is checked is problematic, as SIGHASH_FORKID is also a masking bit. Rather than using >= this whole section dealing with SIGHASH_ANYONECANPAY should be changed to use & operation instead.
https://github.com/OutCast3k/coinbin/blob/master/js/coin.js#L962

4. Add another case for & 64 (0x40) that will handle SIGHASH_FORKID

5. Make sure that when Bitcoin Cash is active, it adds the 0x40 (64) mask to any sighash used.

6. create some methods for the transaction class that return the following:
   a. Concatenated prevout hashes and indexes of each input in order as bytes.
   b. Concatenated sequence bytes of each input in order as bytes.
   c. Concatenated value and scriptPubkey of each output in order as bytes.

7. double sha256 the output of each of those at the beginning. Then format the message for hashing, which is:

```
*1. nVersion of the transaction (4-byte little endian)
 2. hashPrevouts (32-byte hash)
 3. hashSequence (32-byte hash)
*4. outpoint (32-byte hash + 4-byte little endian) 
*5. scriptCode of the input (serialized as scripts inside CTxOuts)
 6. value of the output spent by this input (8-byte little endian)
*7. nSequence of the input (4-byte little endian)
 8. hashOutputs (32-byte hash)
*9. nLocktime of the transaction (4-byte little endian)
*10. sighash type of the signature (4-byte little endian)
```

The stuff with * before them are already existing in the transaction serializer, so you could just serialize the transaction and splice in the new stuff needed...

Anywho, good luck.

**Comment by OutCast3k** [comment]
@dabura667 (and everyone else) nice work, currently reviewing the pull request and everything else etc.

**Comment by dabura667** [comment]
@OutCast3k oh btw, my PR only currently works for SIGHASH_ALL...

No one has yet to come and complain, so I have left as is.

Also, it might be better to encode the value in the unsigned transaction rather than fetching the API utxos every time you sign the transaction lol.

**Pull request closed without merging**
